import { Footer } from '@/components/main/Footer'
import { TopNav } from '../components/main/TopNav'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <TopNav />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
